version: '2'
services:
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scheduler
    ports:
      - '3316:3306'
    volumes_from:
      - datastore

  datastore:
    image: busybox
    volumes:
      - scheduler-data:/var/lib/mysql

  redis:
    image: redis:2.8.19
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/scheduler
      - bundle_path:/vendor/bundle
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/vendor/bundle
      - BUNDLE_APP_CONFIG=/scheduler/.bundle
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/scheduler
      - bundle_path:/vendor/bundle
    environment:
      - BUNDLE_PATH=/vendor/bundle
      - BUNDLE_APP_CONFIG=/scheduler/.bundle
    depends_on:
      - db
      - redis

volumes:
  scheduler-data:
    driver: local
  bundle_path:
    driver: local
  redis-data:
    driver: local
