version: '3'
services:
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scheduler
    volumes:
      - scheduler-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - '80:80'

volumes:
  scheduler-data: {}
