swagger: '2.0'
info:
  description: This document is Monthly Report API Specification.
  version: 1.0.0
  title: Monthly Report API
  contact:
    email: masashi@masacode.co
# host: faces-rekognition.liquidinc.asia
basePath: /api/v1
tags:
  - name: Monthly Reports
    description: 'keep track of your work hour monthly'
schemes:
  - https
paths:
  '/monthly_reports':
    get: 
      summary: Get all the monthly reports for the user
      tags: 
        - Monthly Reports
      parameters: 
        - in: header
          name: access_token
          description: Authentication token to access resource
          required: true
          type: string
      responses:
        '200':
          description: Returns success message when succeed getting all the monthly reports for user
          schema:
            properties:
              reports: 
                type: object
                description: all the records for the user
                example: [
                    {
                      id: 1,
                      user_id: 1,
                      data: "{record_date: '2018-01-01' worked_hour: 8},{record_date: '2018-01-02', worked_hour: 10}",
                      total_hour: 18,
                      total_days: 2,
                      average_hour: 9.0,
                      period_month: 1,
                      period_year: 2018,
                    }
                  ]
  '/monthly_reports/{id}':
    get:
      summary: Get specific month's report for the user
      tags: 
        - Monthly Reports
      parameters: 
        - in: header
          name: access_token
          description: Authentication token to access resource
          required: true
          type: string
        - in: path
          description: Monthly report's id
          name: id
          type: integer
          required: true
      responses:
        '200':
          description: Returns success message when succeed getting all the monthly reports for user
          schema:
            properties:
              report: 
                type: object
                description: all the records for the user
                example: {
                      id: 1,
                      user_id: 1,
                      data: "{record_date: '2018-01-01' worked_hour: 8},{record_date: '2018-01-02', worked_hour: 10}",
                      total_hour: 18,
                      total_days: 2,
                      average_hour: 9.0,
                      period_month: 1,
                      period_year: 2018,
                    }
        '404':
          description: Return this error when reports was not found
          schema:
            properties:
              message:
                type: string
                description: error message
                example: "Couldn't find MonthlyReport with 'id'=0"
